version: '3'
services:
  frontend:
    build: ./OLA-5-FrontEnd
    ports: 
      - "3000:3000"
  # Nest.js application
  backend:
    build: ./OLA-5-Server
    ports:
      - "8080:8080" # Map the host port to the container port
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017" # Map the host port to the container port
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password # Set your desired password here
    volumes:
      - mongo-data:/data/hotels # Persist data by using volumes

volumes:
  mongo-data:
