version: '3'
services:
# Next.js application
  frontend:
    build: ./OLA-5-FrontEnd
    ports: 
      - "3000:3000"
  # Nest.js application
  backend:
    build: ./OLA-5-Server
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes:
      - mongo-data:/data/hotels # Utilizes the defined volume 'mongo-data' to persist MongoDB data withing the container at the path '/data/hotels'

volumes:
  mongo-data: # Creates a volume named 'mongo-data' that can be used by any service in the .yml file.
